### PR TITLE
Fix styling in markers tab

### PR DESCRIPTION
**Pull request by sw-jakobgepp**
HTML formatting is not supported any more for the markers tab.
See [here](https://github.com/rstudio/rstudio/issues/10062) for details.
Therefore, only using the terminal colors work now also in the markers tab.

With the fix, the colors are shown again, but the `<-` is still displayed as `&lt;`.

PS: tests might fail in Github actions due to old testing setup
Local tests were fine: `[ FAIL 0 | WARN 0 | SKIP 0 | PASS 139 ]`

### CODE REVIEW

**Comment by sw-jakobgepp** [comment]
For Github Action workflow adjustment you might want to check [here](https://github.com/Dschaykib/newsmd/tree/master/.github/workflows).

**Comment by mnist91** [comment]
Thanks for the request. Any reasons/downsides why not to exclude lines [95-97](https://github.com/mnist91/origin/blob/1515bd1ccd0dd630e6f70e03420dd6b4b1ee65c5/R/fix_html_tokens.R#L95) to show `<-` properly?

Additionally, since it got released with [2023.03.0 (Fixed rendering of custom source markers (#12425))](https://docs.posit.co/ide/news/#rstudio-ide-10), I will make it depending on the rstudio-version via
```
rstudioapi::versionInfo()$version >= "2023.03.0"
```

**Comment by sw-jakobgepp** [comment]
No real reason, I just did a quick fix without deeper looking into it :)

**Comment by mnist91** [comment]
desired behaviour was implemented in the 1.1.2 version

**Pull request closed without merging**
